name: Hexo Deploy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: source

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node modules # step2
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        # if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "nickqiaoo@gmail.com"
          git config --global user.name "Nickqiaoo"
          npm install hexo-cli -g
          npm install
          npm install --save hexo-helper-live2d
          npm install live2d-widget-model-haru
          cd node_modules/live2d-widget-model-haru/
          cp package.json 02/
          cd ../..

      - name: Deploy
        run: |
          hexo clean
          hexo deploy